site_name: Heart Disease MLOps
site_description: Project documentation
repo_url: https://github.com/${GITHUB_REPOSITORY}
repo_name: ${GITHUB_REPOSITORY}

docs_dir: doc
site_dir: site

# When opening built docs directly from disk (file://), directory URLs can show a folder listing
# instead of index.html. Disabling this generates `page.html` files.
use_directory_urls: false

theme:
  name: material

nav:
  - Home: index.md
  - EDA: eda.md
  - Modeling: modeling.md
  - Experiment Tracking: experiment-tracking.md

markdown_extensions:
  - toc:
      permalink: true
